<a href="https://colab.research.google.com/github/MinerHorst/DeepLearningPytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pytorch Fundamentals**

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu121


In [2]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [14]:
scalar.shape

torch.Size([])

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor([[7,8],
 [9, 10]])
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX[0]

tensor([7, 8])

In [15]:
MATRIX.item

<function Tensor.item>

In [16]:
TENSOR = torch.tensor([[[1, 2, 3],[3, 6, 9],[2, 4, 5]]])

In [17]:
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [30]:
TENSOR = torch.tensor([[[
                        [1,2,3],
                        [1,2,3],
                        [1,2,3]]]])

In [25]:
TENSOR

tensor([[[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]]])

In [26]:
TENSOR.ndim

4

In [28]:
TENSOR.shape

torch.Size([1, 1, 3, 3])

In [43]:
random_tensor = torch.rand(3, 4)

In [44]:
random_tensor

tensor([[0.3940, 0.2017, 0.5250, 0.5800],
        [0.7699, 0.5011, 0.9339, 0.4871],
        [0.3356, 0.2000, 0.9815, 0.8371]])

In [45]:
random_tensor.ndim

2

In [46]:
random_image_size_tensor = torch.rand(size=(224,224,3))

In [47]:
random_image_size_tensor

tensor([[[0.2264, 0.5807, 0.2749],
         [0.2670, 0.8831, 0.5291],
         [0.5849, 0.7219, 0.6190],
         ...,
         [0.2158, 0.6321, 0.3703],
         [0.3675, 0.8577, 0.6565],
         [0.2629, 0.0973, 0.4453]],

        [[0.6011, 0.2350, 0.3662],
         [0.1772, 0.1149, 0.4832],
         [0.1329, 0.9242, 0.0229],
         ...,
         [0.6950, 0.5717, 0.7460],
         [0.1952, 0.2464, 0.4728],
         [0.3909, 0.9892, 0.8302]],

        [[0.1895, 0.1275, 0.9175],
         [0.4349, 0.5200, 0.3294],
         [0.7708, 0.3685, 0.2375],
         ...,
         [0.1859, 0.2449, 0.3165],
         [0.9481, 0.3878, 0.4978],
         [0.6119, 0.0125, 0.7390]],

        ...,

        [[0.1393, 0.4930, 0.4143],
         [0.0430, 0.0743, 0.4115],
         [0.9344, 0.0292, 0.6241],
         ...,
         [0.9648, 0.6499, 0.4305],
         [0.5386, 0.5982, 0.1578],
         [0.1124, 0.6103, 0.0064]],

        [[0.0039, 0.3015, 0.2345],
         [0.8448, 0.7452, 0.9888],
         [0.

In [49]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [50]:
zeros = torch.zeros(size=(3,4))

In [51]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [52]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [54]:
ones = torch.ones(size=[3,4])

In [55]:
ones.dtype

torch.float32

In [56]:
ones * random_tensor

tensor([[0.3940, 0.2017, 0.5250, 0.5800],
        [0.7699, 0.5011, 0.9339, 0.4871],
        [0.3356, 0.2000, 0.9815, 0.8371]])

In [64]:
one_to_ten = torch.arange(start=1, end=10, step=1)

In [65]:
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
#Creating tensors like

one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
ten_zeros = torch.zeros_like(input=one_to_ten)

In [69]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])